name: It's a keng
description: How to avoid it? Where is it?
title: "[keng]: "
labels: [keng]
assignees:
  - naive_scrooge
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share this keng!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A keng"
    validations:
      required: true
